name: Deploy to ECS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/callmates' && 'production' || 'staging' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine Environment
        id: determine-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/callmates" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get ECR URL from SSM Parameter Store
        id: get_ecr_url
        run: |
          ECR_URL=$(aws ssm get-parameter --name "/${{ env.ENVIRONMENT }}/${{ vars.APP_NAME }}/ecr-url" --query "Parameter.Value" --output text)
          echo "ECR_URL=${ECR_URL}" >> $GITHUB_ENV

      - name: Get ECS Cluster Name from SSM Parameter Store
        id: get_ecs_cluster_name
        run: |
          ECS_CLUSTER_NAME=$(aws ssm get-parameter --name "/${{ env.ENVIRONMENT }}/cluster-name" --query "Parameter.Value" --output text)
          echo "ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME}" >> $GITHUB_ENV

      - name: Get ECS Service Name from SSM Parameter Store
        id: get_ecs_service_name
        run: |
          ECS_SERVICE_NAME=$(aws ssm get-parameter --name "/${{ env.ENVIRONMENT }}/${{ vars.APP_NAME }}/service-name" --query "Parameter.Value" --output text)
          echo "ECS_SERVICE_NAME=${ECS_SERVICE_NAME}" >> $GITHUB_ENV

      - name: Get ECS Task Family from SSM Parameter Store
        id: get_ecs_task_family
        run: |
          ECS_TASK_FAMILY=$(aws ssm get-parameter --name "/${{ env.ENVIRONMENT }}/${{ vars.APP_NAME }}/task-family" --query "Parameter.Value" --output text)
          echo "ECS_TASK_FAMILY=${ECS_TASK_FAMILY}" >> $GITHUB_ENV

      - name: Get Container Name from SSM Parameter Store
        id: get_container_name
        run: |
          CONTAINER_NAME=$(aws ssm get-parameter --name "/${{ env.ENVIRONMENT }}/${{ vars.APP_NAME }}/container-name" --query "Parameter.Value" --output text)
          echo "CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build-image
        run: |
          docker build -f ./docker/app.Dockerfile -t ${{ env.ECR_URL }}:latest .
          docker push ${{ env.ECR_URL }}:latest

      - name: Update ECS service
        id: update-ecs
        run: |
          # Retrieve the current task definition
          CURRENT_TASK_DEF=$(aws ecs describe-task-definition --task-definition $ECS_TASK_FAMILY)

          # Use jq to update the task definition correctly by omitting fields with 'null' values and updating the image URL
          NEW_TASK_DEF=$(echo "$CURRENT_TASK_DEF" | jq '
            .taskDefinition
            | { family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory }
            | .containerDefinitions[0].image = "'${ECR_URL}:latest'"
            | del(.containerDefinitions[].cpu, .containerDefinitions[].memory, .containerDefinitions[].environment, .containerDefinitions[].secrets)
            | del(.pidMode, .ipcMode, .proxyConfiguration, .inferenceAccelerators, .ephemeralStorage, .runtimePlatform)
          ')

          echo "New Task Definition:"
          echo "$NEW_TASK_DEF"

          # Create new task definition revision
          echo $NEW_TASK_DEF > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

          # Update the ECS service to use the new task definition
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
